### PR TITLE
feat(list-repos): add script to list repos

### PR DESCRIPTION
**Pull request by slack**
Run `list-repos` to fetch a list of deis-prefixed repositories that can then be
fed into `seed-repo`.

Run `list-repos -x` to spit out a list of "rejected" repositories.

### CODE REVIEW

**Comment by slack** [comment]
Included repos:

```
$ be ruby list-repos
deis/builder
deis/charts
deis/controller
deis/deployment
deis/distribution
deis/dockerbuilder
deis/fluentd
deis/gutenberg
deis/jenkins-jobs
deis/k8s-claimer
deis/logger
deis/minio
deis/mock-http-server
deis/monitor
deis/mortician
deis/object-storage-cli
deis/postgres
deis/registry
deis/router
deis/slugbuilder
deis/slugrunner
deis/syslogparser
deis/telegraf
deis/workflow
deis/workflow-cli
deis/workflow-e2e
deis/workflow-manager
deis/workflow-manager-api
```

Excluded repos:

```
$ be ruby list-repos  -x
deis/confd
deis/deis
deis/deis.io
deis/django-fsm
deis/django-polls
deis/docker-go-dev
deis/docker-go-test
deis/docker-python-dev
deis/docker-registry
deis/etcd
deis/example-clojure-ring
deis/example-dockerfile-http
deis/example-dockerfile-python
deis/example-go
deis/example-java-jetty
deis/example-nodejs-express
deis/example-perl
deis/example-php
deis/example-play
deis/example-python-django
deis/example-python-flask
deis/example-ruby-sinatra
deis/example-scala
deis/example-spree
deis/helloworld
deis/helm-dm
deis/informant
deis/makeself
deis/memkv
deis/minio-src
deis/minio-sync
deis/nginxpusher
deis/pkg
deis/presentation-template
deis/prototype-repo
deis/redis-cluster
deis/riak
deis/riemann
deis/rigger
deis/seed-repo
deis/swarm
deis/template-project
deis/tips-n-tricks
deis/training
deis/update-watcher
deis/wal-e
```

**Comment by arschles** [comment]
@slack why is `deis/wal-e` excluded? Same with `deis/prototype-repo`

**Comment by slack** [comment]
Wasn't sure if we wanted it to follow the beta1/beta2 stuff since it is a fork of upstream...  Happy to add it if it should go in the box. :dancer:

**Comment by mboersma** [comment]
:+1: for adding wal-e and prototype-repo, in this or a future PR.

**Comment by arschles** [comment]
@slack k, good pt. LGTM3

**Pull request merged**
